# configs/prod.yaml

server:
  port: 8081
  debug: false
database:
  host: 47.100.124.57
  port: 3306
  dbname: gaet 
  username: gaet
  password: IifC5KF0
jwt:
  key: 123123

redis:
  host: "127.0.0.1:6379"
  password: ""
  max_idle: 30
  max_active: 30
  idle_timeout: 200
