definitions:
  controllers.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.Article:
    properties:
      commentCount:
        type: integer
      comments:
        items:
          $ref: '#/definitions/models.Comment'
        type: array
      content:
        type: string
      cover:
        type: string
      createdAt:
        type: string
      desc:
        type: string
      id:
        type: integer
      mark:
        type: string
      readCount:
        type: integer
      sort:
        type: integer
      source:
        type: string
      starCount:
        type: integer
      stars:
        items:
          $ref: '#/definitions/models.Star'
        type: array
      status:
        type: boolean
      title:
        type: string
      type:
        type: integer
      updatedAt:
        type: string
      video:
        type: string
    type: object
  models.Comment:
    properties:
      articleID:
        type: integer
      content:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/models.ResponseUser'
        description: 使用ResponseUser类型
      userID:
        type: integer
    type: object
  models.ResponseUser:
    properties:
      avatar:
        type: string
      id:
        type: integer
      phone:
        type: string
      username:
        type: string
    type: object
  models.Star:
    properties:
      articleID:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/models.ResponseUser'
        description: 定义与 User 模型的关联
      userID:
        type: integer
      username:
        description: 不映射到数据库，用于存储用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /article:
    get:
      consumes:
      - application/json
      description: 根据文章ID获取文章详情
      parameters:
      - description: 文章ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Article'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: 获取文章详情 type=1表示文章，type=2表示视频。视频在列表点击直接播放
      tags:
      - Articles
  /articles:
    get:
      consumes:
      - application/json
      description: 获取文章列表，支持分页查询
      parameters:
      - description: 页码 (默认为1)
        in: query
        name: page
        type: integer
      - description: 每页显示数量 (默认为10)
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: 获取文章列表
      tags:
      - Articles
  /test/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
swagger: "2.0"
